name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        example: [examples/CleanTag/CleanTag.ino, examples/EraseTag/EraseTag.ino, examples/FormatTag/FormatTag.ino, 
          examples/ReadTag/ReadTag.ino, examples/ReadTagExtended/ReadTagExtended.ino, examples/WriteTag/WriteTag.ino, 
          examples/WriteTagMultipleRecords/WriteTagMultipleRecords.ino]

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        pio lib -g install "miguelbalboa/MFRC522"

    - name: Run PlatformIO
      run: pio ci --board=atmelavr --board=ststm32 --board=espressif8266 --board=espressif32 --board=samd
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}